CREATE SCHEMA IF NOT EXISTS MA_STUDENT;
DROP TABLE IF EXISTS MA_STUDENT.CUSTOMERS;

CREATE TABLE MA_STUDENT.CUSTOMERS(
    "CUST_NUM" DECIMAL PRIMARY KEY,
	"COMPANY" VARCHAR2(40),
	"CUST_REP" DECIMAL,
	"CREDIT_LIMIT" DECIMAL,);
